use_frameworks!

platform :ios, '9.0'

target 'SYDCentralPivot_Example' do
  pod 'SYDCentralPivot', :path => '../', :subspecs => ['Core']

  target 'SYDCentralPivot_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
